### ISSUE TITLE
Sayfa içeriği küçük ekranlarda gözükmüyor

### ISSUE THREAD

**Issue by ertugrulungor** [dnomak/responsive-test#1]
Tarayıcı genişliği 922 pikselin altına küçültüldüğünde -mobil ekranlar ve tabletlerde- içerik gözükmüyor.

**Comment by dnomak** [comment]
evet o kısım için bir açıklama yazmam gerekiyordu fakat atlamışım sonradan da unuttum teşekkürler :)

**Comment by ertugrulungor** [comment]
Rica ederim 👍
